# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemosyne" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "13e8148d8def3149e21c837aada7f4d23a44a00d894f81597ab6e9c16daa74a4"
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b3b8246666312d7403cd4bcf7496c8c8041979f09a0acc69eb0f576b24947be"
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0f3bfe483e6d5b9ec786652bf706a92f1f7a8aa4a7296a29e316b4d8d7fd598"
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9f9696713ad8cc9c1d5edd14d9f629393cd3957dbce607dbfa31b9bf7f306ca2"
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemosyne"
  desc "Export coding-assistant histories to unified, anonymized archives."
  homepage "https://github.com/AletheiaResearch/mnemosyne"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "hf",
    ]

  binary "mnemosyne"
  manpage "man/man1/mnemosyne-attest.1"
  manpage "man/man1/mnemosyne-configure.1"
  manpage "man/man1/mnemosyne-extract.1"
  manpage "man/man1/mnemosyne-inspect.1"
  manpage "man/man1/mnemosyne-publish.1"
  manpage "man/man1/mnemosyne-runlog.1"
  manpage "man/man1/mnemosyne-serializers.1"
  manpage "man/man1/mnemosyne-survey.1"
  manpage "man/man1/mnemosyne-templates.1"
  manpage "man/man1/mnemosyne-transform.1"
  manpage "man/man1/mnemosyne-validate.1"
  manpage "man/man1/mnemosyne.1"

  postflight do
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/mnemosyne", "#{HOMEBREW_PREFIX}/bin/mem"
  end

  uninstall_postflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/mem"
  end

  # No zap stanza required

end
