# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemosyne" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_darwin_amd64.tar.gz"
      sha256 "4391ade301f782013347c817ccb3b193d46fdec1e02f3f5a03f29f92078512b4"
    end
    on_arm do
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_darwin_arm64.tar.gz"
      sha256 "5090b199b52bbe06430cdcaaf79f58e0ce0680c0ad6f8ada396e8fab61e201c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_linux_amd64.tar.gz"
      sha256 "cf4813c359d68fa8f74b6ddb3095b853550bded63110ccf5564d1bdeac5b8db3"
    end
    on_arm do
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_linux_arm64.tar.gz"
      sha256 "39f8644b8a9bc959c57a333464ba45747254f589fb3a535d061334fdc98ad032"
    end
  end

  name "mnemosyne"
  desc "Export coding-assistant histories to unified, anonymized archives."
  homepage "https://github.com/AletheiaResearch/mnemosyne"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "hf",
    ]

  binary "mnemosyne"

  postflight do
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/mnemosyne", "#{HOMEBREW_PREFIX}/bin/mem"
  end

  uninstall_postflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/mem"
  end

  # No zap stanza required

end
