# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemosyne@0.3.0" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "9f7e5264aa13a5f2e758c4797fb78d15ddd854facf59d474c9a366af7a141054"
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f019068c5eafebda8f607a0defcf82c7c04e5d3516476d4e03d9afc3c1c2427c"
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ac29fed84b948f0bfe54fcdecff8f9a026b32d502b48032fe9f57eee8247520"
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "084b306dd6826d52b967a621e72627e66aced4c15089348e0bec7c45eee380a9"
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemosyne@0.3.0"
  desc "Export coding-assistant histories to unified, anonymized archives."
  homepage "https://github.com/AletheiaResearch/mnemosyne"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "hf",
    ]

  binary "mnemosyne"
  manpage "man/man1/mnemosyne-attest.1"
  manpage "man/man1/mnemosyne-configure.1"
  manpage "man/man1/mnemosyne-extract.1"
  manpage "man/man1/mnemosyne-inspect.1"
  manpage "man/man1/mnemosyne-publish.1"
  manpage "man/man1/mnemosyne-runlog.1"
  manpage "man/man1/mnemosyne-serializers.1"
  manpage "man/man1/mnemosyne-survey.1"
  manpage "man/man1/mnemosyne-templates.1"
  manpage "man/man1/mnemosyne-transform.1"
  manpage "man/man1/mnemosyne-validate.1"
  manpage "man/man1/mnemosyne.1"

  # No zap stanza required

end
