# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemosyne" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_darwin_amd64.tar.gz"
      sha256 "6919d58795e95e4025128ff3fd6a91d5d7961c1aa3a239a4f18041038dda9484"
    end
    on_arm do
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_darwin_arm64.tar.gz"
      sha256 "71bda2caf9b9b2a97e92a07854ca9a2a19658bbd420a1ab6ad1510a45b0e58be"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_linux_amd64.tar.gz"
      sha256 "a3e859d22eb30c101105c298271363e7d8158c1732812e97b9a7a85bc52679e2"
    end
    on_arm do
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_linux_arm64.tar.gz"
      sha256 "46f839b89f7fad5195d749f2ab98622b196e79098d1ddb7e52a9f0e37d5c7dad"
    end
  end

  name "mnemosyne"
  desc "Export coding-assistant histories to unified, anonymized archives."
  homepage "https://github.com/AletheiaResearch/mnemosyne"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemosyne"

  postflight do
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/mnemosyne", "#{HOMEBREW_PREFIX}/bin/mem"
  end

  uninstall_postflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/mem"
  end

  # No zap stanza required

end
