# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemosyne@0.4.0" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "5663c0535c5a885743e4763ef6d2da153804b0810b59c63dfb088dab59e90a48"
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6f7415826f35ba1c73186177e568048f788edb6253f42f564dc000d1b02b18b"
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ff398e442495d6e2fbe874def1a09e15bd330f2f6d1c437908fcd4ced24b4e98"
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c11c7b4235fb23496b3b8992063a2b8138d5c1bcfbcf46cc3d1fc14dfffcf30c"
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v#{version}/mnemosyne_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemosyne@0.4.0"
  desc "Export coding-assistant histories to unified, anonymized archives."
  homepage "https://github.com/AletheiaResearch/mnemosyne"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "hf",
    ]

  binary "mnemosyne"
  manpage "man/man1/mnemosyne-attest.1"
  manpage "man/man1/mnemosyne-configure.1"
  manpage "man/man1/mnemosyne-extract.1"
  manpage "man/man1/mnemosyne-inspect.1"
  manpage "man/man1/mnemosyne-publish.1"
  manpage "man/man1/mnemosyne-runlog.1"
  manpage "man/man1/mnemosyne-serializers.1"
  manpage "man/man1/mnemosyne-survey.1"
  manpage "man/man1/mnemosyne-templates.1"
  manpage "man/man1/mnemosyne-transform.1"
  manpage "man/man1/mnemosyne-validate.1"
  manpage "man/man1/mnemosyne.1"

  # No zap stanza required

end
