# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemosyne < Formula
  desc "Export coding-assistant histories to unified, anonymized archives."
  homepage "https://github.com/AletheiaResearch/mnemosyne"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v0.1.1/mnemosyne_0.1.1_darwin_amd64.tar.gz"
      sha256 "a28659d441ebd361555bbb236048b10dfa70ea656af0ab9d182083985be8de9c"

      define_method(:install) do
        bin.install "mnemosyne"
        bin.install_symlink "mnemosyne" => "mem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v0.1.1/mnemosyne_0.1.1_darwin_arm64.tar.gz"
      sha256 "a7f70388f0279b51f66566427b8400371ffb6c33d80229019ecb6b74fe320d02"

      define_method(:install) do
        bin.install "mnemosyne"
        bin.install_symlink "mnemosyne" => "mem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v0.1.1/mnemosyne_0.1.1_linux_amd64.tar.gz"
      sha256 "61d7f05b6faf877deff2003b6d728c3dc368d5931f05fa2a7c80e696c530f9f0"
      define_method(:install) do
        bin.install "mnemosyne"
        bin.install_symlink "mnemosyne" => "mem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v0.1.1/mnemosyne_0.1.1_linux_arm64.tar.gz"
      sha256 "b76e34c48c35f072bea38ecaa8726f3773bf182c40a625998aaaa5b4f8a0ecb4"
      define_method(:install) do
        bin.install "mnemosyne"
        bin.install_symlink "mnemosyne" => "mem"
      end
    end
  end
end
