# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemosyne < Formula
  desc "Export coding-assistant histories to unified, anonymized archives."
  homepage "https://github.com/AletheiaResearch/mnemosyne"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v0.1.0/mnemosyne_0.1.0_darwin_amd64.tar.gz"
      sha256 "3a5cd72c0ef30f73af5fd3a5a19f7008ab7082ceb711879b879ca5881a87e174"

      define_method(:install) do
        bin.install "mnemosyne"
        bin.install_symlink "mnemosyne" => "mem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v0.1.0/mnemosyne_0.1.0_darwin_arm64.tar.gz"
      sha256 "ab62b3a0fcb5c4d31cc583a29c5de693ccfa336ed287479da813cc7b26f3d178"

      define_method(:install) do
        bin.install "mnemosyne"
        bin.install_symlink "mnemosyne" => "mem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v0.1.0/mnemosyne_0.1.0_linux_amd64.tar.gz"
      sha256 "ce16b4fe868f2cce8c6e192485ee61bb51fe92f4d38a8e17d29a381abe6864fe"
      define_method(:install) do
        bin.install "mnemosyne"
        bin.install_symlink "mnemosyne" => "mem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AletheiaResearch/mnemosyne/releases/download/v0.1.0/mnemosyne_0.1.0_linux_arm64.tar.gz"
      sha256 "a16b7cd017ed7b33f141a8d9223e2ad1edfa1d6411b983a4d1a1feb6564a95b4"
      define_method(:install) do
        bin.install "mnemosyne"
        bin.install_symlink "mnemosyne" => "mem"
      end
    end
  end
end
